version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
            - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
            - "8090:80"
    volumes:
            - www_data:/var/www/html
    networks:
      - backend
      - proxy
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    deploy:
      labels:
        traefik.port: 8090
        traefik.frontend.rule: "Host:toniwp.192.168.20.201.nip.io,toniwp.192.168.20.202.nip.io,toniwp.192.168.20.203.nip.io"
        traefik.docker.network: 'proxy'

volumes:
    db_data:
      driver_opts:
        type: "nfs"
        o: "addr=192.168.20.203,nolock,soft,rw"
        device: ":/srv/nfs/volumes/tonidb/dbdata"
    www_data:
      driver_opts:
        type: "nfs"
        o: "addr=192.168.20.203,nolock,soft,rw"
        device: ":/srv/nfs/volumes/toniwp/www"


networks:
  backend:
  proxy:
    external: true
